DROP TABLE IF EXISTS animals CASCADE;
DROP TABLE IF EXISTS species;

CREATE TABLE animals (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    nickname TEXT NOT NULL
);

CREATE TABLE species (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    type_id BIGINT,
    FOREIGN KEY(type_id) REFERENCES animals(id)
);